language: java
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
  - unzip -qq apache-maven-3.5.3-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.3
  - export PATH=$M2_HOME/bin:$PATH
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn -B -P test test
