name: tck-webprofile
on:
  push:
    paths:
      - 'external/webprofile-tck/**'
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:
    paths:
      - 'external/webprofile-tck/**'
    branches:
      - '*'  
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  atinject:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/webprofile-tck/atinject
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/webprofile-tck/atinject/target/tck/example/target/surefire-reports/TEST-*.xml"
      if: always()
  cdi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/webprofile-tck/cdi
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/webprofile-tck/cdi/runner/target/surefire-reports/junitreports/TEST-*.xml"
      if: always()
  jsonb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/webprofile-tck/jsonb
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "external/webprofile-tck/jsonb/target/tck/bin/target/surefire-reports/TEST-*.xml"
      if: always()
  jsonp:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '21' ]
        os: [ubuntu-latest]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Setup for TCK
      run: mvn -B -DskipTests=true -ntp install
    - name: Run TCK
      run: |
        cd external/webprofile-tck/jsonp
        mvn -B -ntp verify
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          external/webprofile-tck/jsonp/target/tck/bin/tck-tests/target/surefire-reports/TEST-*.xml
          external/webprofile-tck/jsonp/target/tck/bin/tck-tests-pluggability/target/surefire-reports/TEST-*.xml
      if: always()
